server.port=8081
log4j.logger.org.dozer=OFF
spring.security.oauth2.client.registration.google.client-id=685440009263-9k0l1dk8eoj6flgcs2fl985ad987j3lp.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=73xZ7-AsVS6y5v2IAEZ65ItV
spring.security.oauth2.client.registration.google.redirect-uri=http://localhost:8081/oauth2/callback/google

spring.security.oauth2.client.registration.facebook.client-id=540438673220082
spring.security.oauth2.client.registration.facebook.client-secret=007a4d626fbedb2dfb6b64d3f2d2b61c

spring.main.allow-bean-definition-overriding=true
spring.jpa.hibernate.ddl-auto=create
spring.jpa.database-platform=org.hibernate.dialect.MySQL5InnoDBDialect
spring.datasource.platform=mysql
spring.datasource.username=root
spring.jpa.generate-ddl=true
spring.datasource.initialization-mode=always
spring.datasource.password=saya@Mysql5@an
spring.datasource.url=jdbc:mysql://localhost:3306/mysecuredapp?createDatabaseIfNotExist=true&useSSL=true